---
- name: vscode - Set gpg key from '{{ vscode_gpg_key_url }}'
  apt_key:
    url: "{{ vscode_gpg_key_url }}"
    state: present

- name: vscode - Add VS Code reporsitory
  copy:
    content: "deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main"
    dest: /etc/apt/sources.list.d/vscode.list
    group: root
    owner: root
    mode: '0644'

- name: vscode - Install VS Code
  apt:
    name: code
    update_cache: true
